# Activity types found in Yuh ACTIVITIES_REPORT-*.CSV exports.

BANK_AUTO_ORDER_EXECUTED = "BANK_AUTO_ORDER_EXECUTED"
BANK_ORDER_EXECUTED = "BANK_ORDER_EXECUTED"
CASH_TRANSACTION_OTHER = "CASH_TRANSACTION_OTHER"
CASH_TRANSACTION_RELATED_OTHER = "CASH_TRANSACTION_RELATED_OTHER"
INVEST_ORDER_EXECUTED = "INVEST_ORDER_EXECUTED"
INVEST_RECURRING_ORDER_EXECUTED = "INVEST_RECURRING_ORDER_EXECUTED"
INVEST_RECURRING_ORDER_REJECTED = "INVEST_RECURRING_ORDER_REJECTED"
PAYMENT_TRANSACTION_IN = "PAYMENT_TRANSACTION_IN"
PAYMENT_TRANSACTION_OUT = "PAYMENT_TRANSACTION_OUT"
REWARD_RECEIVED = "REWARD_RECEIVED"

ACTIVITY_TYPES = {
    BANK_AUTO_ORDER_EXECUTED,
    BANK_ORDER_EXECUTED,
    CASH_TRANSACTION_OTHER,
    CASH_TRANSACTION_RELATED_OTHER,
    INVEST_ORDER_EXECUTED,
    INVEST_RECURRING_ORDER_EXECUTED,
    INVEST_RECURRING_ORDER_REJECTED,
    PAYMENT_TRANSACTION_IN,
    PAYMENT_TRANSACTION_OUT,
    REWARD_RECEIVED,
}
